# Generated by Django 5.0.6 on 2024-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_bookinginfor_booking_source_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=100)),
                ('discount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
