# Generated by Django 5.0.6 on 2024-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfor',
            name='payment_for_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
