# Generated by Django 5.0.6 on 2024-06-06 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookinginfor_payment_for_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttraninfor',
            name='booking_infor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.bookinginfor'),
        ),
    ]
